name: Docker – Onix Attack-Map

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/arandano-partners/onix-attack-map
  # Bump manually when you tag a new release or read it
  # from version.json via `jq` if you prefer.
  APP_VERSION: "2.2.6"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: cache Docker layers across builds
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
